### PR TITLE
CMakeLists.txt: Fix CMake builds

### PR DESCRIPTION
**Pull request by erikinkinen**
Replace the in-tree cmake files with a full build config to build out-of-tree

### CODE REVIEW

**Comment by Herrie82** [comment]
@shr-project @Tofee Build tested here, output IPK is the same.

**Comment by Tofee** [comment]
So I'm not sure, what does it fix? We have to keep in mind that this repo is an extract from qtsensors, so introducing changes means we'll have to maintain them when sync'ing with qtsensors.

**Comment by Tofee** [comment]
I realize @erikinkinen seems to work on mobian things, so maybe it's fixing a build issue there? If so, I'm ok with the PR.

**Comment by erikinkinen** [comment]
@Tofee , LuneOS still uses qmake to build this although Qt is transitioning to CMake (qmake support may be dropped in future).

The previous CMakeLists.txt only works with in-tree builds while this repository is used for out-of-tree builds.

**Comment by Herrie82** [comment]
@Tofee we're on qmake build still here, merging this, would allow us to move to CMake build too. Seeing the small amount of chnages in the sensorfw code, it's not hard to maintain it when updating stuff from Qt repo.

**Pull request merged**
